### ISSUE TITLE
Add to readme how to run and open the application

### ISSUE THREAD

**Issue by Alex-Mann** [Minres/RDL-Editor#3]
I have downloaded the MacOS source release and have tried running the application, but I get the error:
```
The Eclipse executable launcher was unable to locate its 
companion shared library.
```

Any tips?

**Comment by eyck** [comment]
Hi,
I can reproduce the issue when trying to start it from the FInder or in the Terminal with 'open -f rdl-editor.app'. But when running the eclipse executable in the Terminal directly with './rdl-editor.app/Contents/MacOS/eclipse&' it works fine.
I need to investigate the problem further. Meanwhile you might use the command above.
I'll let you know when I got to some conclusion.
Best regards

**Comment by eyck** [comment]
Seems that something went wrong with the packaging. I uploaded the MacOS X zip file again, so please download it again. After unzipping you should find a rdl-editor app in the eclipse subfolder. Simple run it by double clicking (or right click and select 'Open' to confirm that you want to run an un-verified application).
Please let me know if it works (or not)...
Best regards

**Comment by Mike-Smth** [comment]
I've downloaded the source files but I'm confused about how to actually run this - I don't see the rdl-editor.app that is mentioned above.  How is this actually supposed to be run?

Thanks for your help!
Mike

**Comment by eyck** [comment]
Hi Mike,
did you download https://github.com/Minres/RDL-Editor/releases/download/1_2_0/RDL-Editor-1.2.0-SNAPSHOT-macosx.cocoa.x86_64.tar.gz? The sources do not help much as you need Eclipse DSL tools to build and run the RDL Editor.
Best regards
-Eyck

**Comment by eyck** [comment]
Actually you won't get a rdl-editor.app rather an Eclipse.app to run. I need to check the packaging and will update the readme soon.

-Eyck
