### ISSUE TITLE
standalone generator

### ISSUE THREAD

**Issue by uzleosharif** [Minres/RDL-Editor#6]
I am using the standalone-generator tool for Pulpissimo peripherals. I have a feature request. Currently the tool correctly generates the functional stub for peripheral X having a function `registerResources()` found in `gen/x.h`

```
namespace foo {

class x_regs: 
            public sc_core::sc_module,
            public scc:resetable
{
  // ...
  template<unsigned BUSWIDTH=32>
  void registerResources(scc::tlm_target<BUSWIDTH>& target, uint64_t offset=0);
};

template<unsigned BUSWIDTH>
inline void foo::gen::x_regs::registerResources(scc::tlm_target<BUSWIDTH>& target, uint64_t offset) {
  target.addResource(XYZ, 0x0UL);
  target.addResource(ABC, 0x4UL);
  // ...
}

}
```

i would request to use `offset` in implementation like in the following
```
template<unsigned BUSWIDTH>
inline void foo::gen::x_regs::registerResources(scc::tlm_target<BUSWIDTH>& target, uint64_t offset) {
  target.addResource(XYZ, 0x0UL + offset);
  target.addResource(ABC, 0x4UL + offset);
  // ...
}
```

if there are strong reasons to avoid this then maybe a CLI switch could be provided (like `-ns` for namespace) to enable this. Thanks

**Comment by eyck** [comment]
In principle I don't see an issue with the change,
But to understand it better: what is the reason for this? What is the use case?

**Comment by uzleosharif** [comment]
Hi Eyck, thanks for consideration. Without `+ offset` logic auto generated, the user has to manually do this in generated files if `offset` is not default  `=0`.

Specifically, in pulpissimo simulation the UDMA contains multiple peripherals and uses different `offset` parameter while registering different peripherals like SPI, I2S etc. Without `offset` they would overlap mmap. I feel it won't harm if this is part of generated stub

**Comment by eyck** [comment]
the registerResources function registers the resources at the socket of a tlm_target which belongs to one peripheral. So each peripheral has its own socket. These sockets are then hook to the scc::router instance as can be seen here: https://github.com/Minres/TGC-VP/blob/main/src/tgc_vp/system.cpp#L29 The offsets at the scc::router are generated from the address map entry in the RDL (e.g. https://github.com/VP-Vibes/Pulpissimo-VP/blob/udma-subsys/src/tgc_vp/platform.rdl). So they do not overlap at all....
But your are rigth, having the offset does not harm.

**Comment by uzleosharif** [comment]
yes this makes sense and currently generated output stubs suffice for almost all peripheral modeling scenarios. However, the corner case (one target socket but multiple register sets) is a single peripheral sub-system like UDMA, that connects to rest of SoC as a single peripheral, but internally instantiates multiple (generated) peripherals. For this, `offset` really helps to keep these sub-peripherals' spaces isolated from each other

**Comment by eyck** [comment]
But even in this case the UDMA subsystem gets a router with an internal addressmap and you are good to go. And it makes reusing the peripheral easier. Youd should keep in mind: tlm_target == peripheral

**Comment by uzleosharif** [comment]
router thing looks interesting.. sorry i didn't consider it earlier.. will study more.. thanks for accepting feature request on short notice

**Comment by eyck** [comment]
I think it was a bug anyway since the offset has been used when instantiating a indexed register but not when using a simple register.
